In [10]:
import numpy as np

X=np.array(([5.1,3.5,1.4,0.2],[4.9,3.0,1.4,0.2],[4.7,3.2,1.3,0.2],[4.6,3.1,1.5,0.2],[5.0,3.6,1.4,0.2],[7.0,3.2,4.7,1.4],[6.4,3.2,4.5,1.5],[6.9,3.1,4.9,1.5],[5.5,2.3,4.0,1.3],[6.5,2.8,4.6,1.5]),dtype=float)
y=np.array(([0],[0],[0],[0],[0],[1],[1],[1],[1],[1]),dtype=float)

def Sigmoid(t):
    return 1/(1+np.exp(-t))

def Sigmoid_Derivative(p):
    return p * (1 - p)

class Neural_Network:
    
    def __init__(self, x,y):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1],4) 
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np. zeros(y.shape)
        
    def Feed_Forward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
        
    def Back_Probagation(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*Sigmoid_Derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*Sigmoid_Derivative(self.output), self.weights2.T)*Sigmoid_Derivative(self.layer1))
    
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def Epoch(self, X, y):
        self.output = self.Feed_Forward()
        self.Back_Probagation()

NN = Neural_Network(X,y)

for i in range(1401):

    if i % 1400 == 0:
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.Feed_Forward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.Feed_Forward()))))
        print ("\n")
  
    NN.Epoch(X, y)


for iteration # 0

Input : 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]
Actual Output: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.84019861]
 [0.8395013 ]
 [0.83942003]
 [0.83945966]
 [0.84021601]
 [0.84208966]
 [0.84205898]
 [0.84209919]
 [0.84174695]
 [0.84203775]]
Loss: 
0.3650787384038664


for iteration # 1400

Input : 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]
Actual Output: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.01261111]
 [0.0130131 ]
 [0.01280172]
 [0.01344506]
 [0.01260164]
 [0.9892209 ]
 [0.98930429]
 [0.98965792]
 [0.98952579]
 [0.98963614]]
Loss: 
0.00013865007229052243


